language: python
python:
- 3.5
branches:
  except:
  - gh-pages
install:
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- rm miniconda.sh
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda config --add channels conda-forge
- conda update -q conda
- conda info -a
- conda create -y -q -n convert python=$TRAVIS_PYTHON_VERSION jupyter nbconvert beautifulsoup4
  lxml
- source activate convert
script:
- jupyter nbconvert --to markdown readme.ipynb
- jupyter nbconvert --to python nbd.ipynb
- python nbd.py --to . --deep --ext ipynb --name tonyfast --url https://tonyfast.com/nbd
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
